# stage 1: Build the react application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . .
RUN npm run build

# stage 2: Serve the built application with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /user/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "deamon off;"] 

